//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Diabetes
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DiabetesEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DiabetesEntities object using the connection string found in the 'DiabetesEntities' section of the application configuration file.
        /// </summary>
        public DiabetesEntities() : base("name=DiabetesEntities", "DiabetesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DiabetesEntities object.
        /// </summary>
        public DiabetesEntities(string connectionString) : base(connectionString, "DiabetesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DiabetesEntities object.
        /// </summary>
        public DiabetesEntities(EntityConnection connection) : base(connection, "DiabetesEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BenhNhan> BenhNhans
        {
            get
            {
                if ((_BenhNhans == null))
                {
                    _BenhNhans = base.CreateObjectSet<BenhNhan>("BenhNhans");
                }
                return _BenhNhans;
            }
        }
        private ObjectSet<BenhNhan> _BenhNhans;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<XetNghiem> XetNghiems
        {
            get
            {
                if ((_XetNghiems == null))
                {
                    _XetNghiems = base.CreateObjectSet<XetNghiem>("XetNghiems");
                }
                return _XetNghiems;
            }
        }
        private ObjectSet<XetNghiem> _XetNghiems;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BenhNhans EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBenhNhans(BenhNhan benhNhan)
        {
            base.AddObject("BenhNhans", benhNhan);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the XetNghiems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToXetNghiems(XetNghiem xetNghiem)
        {
            base.AddObject("XetNghiems", xetNghiem);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="BenhNhan")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BenhNhan : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BenhNhan object.
        /// </summary>
        /// <param name="iDKhamBenh">Initial value of the IDKhamBenh property.</param>
        public static BenhNhan CreateBenhNhan(global::System.Int64 iDKhamBenh)
        {
            BenhNhan benhNhan = new BenhNhan();
            benhNhan.IDKhamBenh = iDKhamBenh;
            return benhNhan;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IDKhamBenh
        {
            get
            {
                return _IDKhamBenh;
            }
            set
            {
                if (_IDKhamBenh != value)
                {
                    OnIDKhamBenhChanging(value);
                    ReportPropertyChanging("IDKhamBenh");
                    _IDKhamBenh = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDKhamBenh");
                    OnIDKhamBenhChanged();
                }
            }
        }
        private global::System.Int64 _IDKhamBenh;
        partial void OnIDKhamBenhChanging(global::System.Int64 value);
        partial void OnIDKhamBenhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MaBN
        {
            get
            {
                return _MaBN;
            }
            set
            {
                OnMaBNChanging(value);
                ReportPropertyChanging("MaBN");
                _MaBN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaBN");
                OnMaBNChanged();
            }
        }
        private Nullable<global::System.Decimal> _MaBN;
        partial void OnMaBNChanging(Nullable<global::System.Decimal> value);
        partial void OnMaBNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> NamSinh
        {
            get
            {
                return _NamSinh;
            }
            set
            {
                OnNamSinhChanging(value);
                ReportPropertyChanging("NamSinh");
                _NamSinh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NamSinh");
                OnNamSinhChanged();
            }
        }
        private Nullable<global::System.Decimal> _NamSinh;
        partial void OnNamSinhChanging(Nullable<global::System.Decimal> value);
        partial void OnNamSinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Thon
        {
            get
            {
                return _Thon;
            }
            set
            {
                OnThonChanging(value);
                ReportPropertyChanging("Thon");
                _Thon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Thon");
                OnThonChanged();
            }
        }
        private global::System.String _Thon;
        partial void OnThonChanging(global::System.String value);
        partial void OnThonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenXa
        {
            get
            {
                return _TenXa;
            }
            set
            {
                OnTenXaChanging(value);
                ReportPropertyChanging("TenXa");
                _TenXa = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenXa");
                OnTenXaChanged();
            }
        }
        private global::System.String _TenXa;
        partial void OnTenXaChanging(global::System.String value);
        partial void OnTenXaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenQuan
        {
            get
            {
                return _TenQuan;
            }
            set
            {
                OnTenQuanChanging(value);
                ReportPropertyChanging("TenQuan");
                _TenQuan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenQuan");
                OnTenQuanChanged();
            }
        }
        private global::System.String _TenQuan;
        partial void OnTenQuanChanging(global::System.String value);
        partial void OnTenQuanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenThiTran
        {
            get
            {
                return _TenThiTran;
            }
            set
            {
                OnTenThiTranChanging(value);
                ReportPropertyChanging("TenThiTran");
                _TenThiTran = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenThiTran");
                OnTenThiTranChanged();
            }
        }
        private global::System.String _TenThiTran;
        partial void OnTenThiTranChanging(global::System.String value);
        partial void OnTenThiTranChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenNgheNghiep
        {
            get
            {
                return _TenNgheNghiep;
            }
            set
            {
                OnTenNgheNghiepChanging(value);
                ReportPropertyChanging("TenNgheNghiep");
                _TenNgheNghiep = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenNgheNghiep");
                OnTenNgheNghiepChanged();
            }
        }
        private global::System.String _TenNgheNghiep;
        partial void OnTenNgheNghiepChanging(global::System.String value);
        partial void OnTenNgheNghiepChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayKham
        {
            get
            {
                return _NgayKham;
            }
            set
            {
                OnNgayKhamChanging(value);
                ReportPropertyChanging("NgayKham");
                _NgayKham = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayKham");
                OnNgayKhamChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayKham;
        partial void OnNgayKhamChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayKhamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TenPhongKham
        {
            get
            {
                return _TenPhongKham;
            }
            set
            {
                OnTenPhongKhamChanging(value);
                ReportPropertyChanging("TenPhongKham");
                _TenPhongKham = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TenPhongKham");
                OnTenPhongKhamChanged();
            }
        }
        private global::System.String _TenPhongKham;
        partial void OnTenPhongKhamChanging(global::System.String value);
        partial void OnTenPhongKhamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ChuanDoan
        {
            get
            {
                return _ChuanDoan;
            }
            set
            {
                OnChuanDoanChanging(value);
                ReportPropertyChanging("ChuanDoan");
                _ChuanDoan = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ChuanDoan");
                OnChuanDoanChanged();
            }
        }
        private global::System.String _ChuanDoan;
        partial void OnChuanDoanChanging(global::System.String value);
        partial void OnChuanDoanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> TieuDuong
        {
            get
            {
                return _TieuDuong;
            }
            set
            {
                OnTieuDuongChanging(value);
                ReportPropertyChanging("TieuDuong");
                _TieuDuong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TieuDuong");
                OnTieuDuongChanged();
            }
        }
        private Nullable<global::System.Boolean> _TieuDuong;
        partial void OnTieuDuongChanging(Nullable<global::System.Boolean> value);
        partial void OnTieuDuongChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="XetNghiem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class XetNghiem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new XetNghiem object.
        /// </summary>
        /// <param name="iDXetNghiem">Initial value of the IDXetNghiem property.</param>
        public static XetNghiem CreateXetNghiem(global::System.Int64 iDXetNghiem)
        {
            XetNghiem xetNghiem = new XetNghiem();
            xetNghiem.IDXetNghiem = iDXetNghiem;
            return xetNghiem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 IDXetNghiem
        {
            get
            {
                return _IDXetNghiem;
            }
            set
            {
                if (_IDXetNghiem != value)
                {
                    OnIDXetNghiemChanging(value);
                    ReportPropertyChanging("IDXetNghiem");
                    _IDXetNghiem = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IDXetNghiem");
                    OnIDXetNghiemChanged();
                }
            }
        }
        private global::System.Int64 _IDXetNghiem;
        partial void OnIDXetNghiemChanging(global::System.Int64 value);
        partial void OnIDXetNghiemChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MaBn
        {
            get
            {
                return _MaBn;
            }
            set
            {
                OnMaBnChanging(value);
                ReportPropertyChanging("MaBn");
                _MaBn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaBn");
                OnMaBnChanged();
            }
        }
        private Nullable<global::System.Decimal> _MaBn;
        partial void OnMaBnChanging(Nullable<global::System.Decimal> value);
        partial void OnMaBnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private global::System.String _GioiTinh;
        partial void OnGioiTinhChanging(global::System.String value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> NgayLayMau
        {
            get
            {
                return _NgayLayMau;
            }
            set
            {
                OnNgayLayMauChanging(value);
                ReportPropertyChanging("NgayLayMau");
                _NgayLayMau = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgayLayMau");
                OnNgayLayMauChanged();
            }
        }
        private Nullable<global::System.DateTime> _NgayLayMau;
        partial void OnNgayLayMauChanging(Nullable<global::System.DateTime> value);
        partial void OnNgayLayMauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Cholesterol
        {
            get
            {
                return _Cholesterol;
            }
            set
            {
                OnCholesterolChanging(value);
                ReportPropertyChanging("Cholesterol");
                _Cholesterol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cholesterol");
                OnCholesterolChanged();
            }
        }
        private Nullable<global::System.Decimal> _Cholesterol;
        partial void OnCholesterolChanging(Nullable<global::System.Decimal> value);
        partial void OnCholesterolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HDL_Cholesterol
        {
            get
            {
                return _HDL_Cholesterol;
            }
            set
            {
                OnHDL_CholesterolChanging(value);
                ReportPropertyChanging("HDL_Cholesterol");
                _HDL_Cholesterol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HDL_Cholesterol");
                OnHDL_CholesterolChanged();
            }
        }
        private Nullable<global::System.Decimal> _HDL_Cholesterol;
        partial void OnHDL_CholesterolChanging(Nullable<global::System.Decimal> value);
        partial void OnHDL_CholesterolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Triglyceride
        {
            get
            {
                return _Triglyceride;
            }
            set
            {
                OnTriglycerideChanging(value);
                ReportPropertyChanging("Triglyceride");
                _Triglyceride = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Triglyceride");
                OnTriglycerideChanged();
            }
        }
        private Nullable<global::System.Decimal> _Triglyceride;
        partial void OnTriglycerideChanging(Nullable<global::System.Decimal> value);
        partial void OnTriglycerideChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LDL_Cholesterol
        {
            get
            {
                return _LDL_Cholesterol;
            }
            set
            {
                OnLDL_CholesterolChanging(value);
                ReportPropertyChanging("LDL_Cholesterol");
                _LDL_Cholesterol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LDL_Cholesterol");
                OnLDL_CholesterolChanged();
            }
        }
        private Nullable<global::System.Decimal> _LDL_Cholesterol;
        partial void OnLDL_CholesterolChanging(Nullable<global::System.Decimal> value);
        partial void OnLDL_CholesterolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GGT
        {
            get
            {
                return _GGT;
            }
            set
            {
                OnGGTChanging(value);
                ReportPropertyChanging("GGT");
                _GGT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GGT");
                OnGGTChanged();
            }
        }
        private Nullable<global::System.Decimal> _GGT;
        partial void OnGGTChanging(Nullable<global::System.Decimal> value);
        partial void OnGGTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Glucose
        {
            get
            {
                return _Glucose;
            }
            set
            {
                OnGlucoseChanging(value);
                ReportPropertyChanging("Glucose");
                _Glucose = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Glucose");
                OnGlucoseChanged();
            }
        }
        private Nullable<global::System.Decimal> _Glucose;
        partial void OnGlucoseChanging(Nullable<global::System.Decimal> value);
        partial void OnGlucoseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SGOT
        {
            get
            {
                return _SGOT;
            }
            set
            {
                OnSGOTChanging(value);
                ReportPropertyChanging("SGOT");
                _SGOT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SGOT");
                OnSGOTChanged();
            }
        }
        private Nullable<global::System.Decimal> _SGOT;
        partial void OnSGOTChanging(Nullable<global::System.Decimal> value);
        partial void OnSGOTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> SGPT
        {
            get
            {
                return _SGPT;
            }
            set
            {
                OnSGPTChanging(value);
                ReportPropertyChanging("SGPT");
                _SGPT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SGPT");
                OnSGPTChanged();
            }
        }
        private Nullable<global::System.Decimal> _SGPT;
        partial void OnSGPTChanging(Nullable<global::System.Decimal> value);
        partial void OnSGPTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Urea
        {
            get
            {
                return _Urea;
            }
            set
            {
                OnUreaChanging(value);
                ReportPropertyChanging("Urea");
                _Urea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Urea");
                OnUreaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Urea;
        partial void OnUreaChanging(Nullable<global::System.Decimal> value);
        partial void OnUreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> WBC
        {
            get
            {
                return _WBC;
            }
            set
            {
                OnWBCChanging(value);
                ReportPropertyChanging("WBC");
                _WBC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WBC");
                OnWBCChanged();
            }
        }
        private Nullable<global::System.Decimal> _WBC;
        partial void OnWBCChanging(Nullable<global::System.Decimal> value);
        partial void OnWBCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LYM
        {
            get
            {
                return _LYM;
            }
            set
            {
                OnLYMChanging(value);
                ReportPropertyChanging("LYM");
                _LYM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LYM");
                OnLYMChanged();
            }
        }
        private Nullable<global::System.Decimal> _LYM;
        partial void OnLYMChanging(Nullable<global::System.Decimal> value);
        partial void OnLYMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MONO
        {
            get
            {
                return _MONO;
            }
            set
            {
                OnMONOChanging(value);
                ReportPropertyChanging("MONO");
                _MONO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MONO");
                OnMONOChanged();
            }
        }
        private Nullable<global::System.Decimal> _MONO;
        partial void OnMONOChanging(Nullable<global::System.Decimal> value);
        partial void OnMONOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> GRAN
        {
            get
            {
                return _GRAN;
            }
            set
            {
                OnGRANChanging(value);
                ReportPropertyChanging("GRAN");
                _GRAN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GRAN");
                OnGRANChanged();
            }
        }
        private Nullable<global::System.Decimal> _GRAN;
        partial void OnGRANChanging(Nullable<global::System.Decimal> value);
        partial void OnGRANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TyLeLYM
        {
            get
            {
                return _TyLeLYM;
            }
            set
            {
                OnTyLeLYMChanging(value);
                ReportPropertyChanging("TyLeLYM");
                _TyLeLYM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TyLeLYM");
                OnTyLeLYMChanged();
            }
        }
        private Nullable<global::System.Decimal> _TyLeLYM;
        partial void OnTyLeLYMChanging(Nullable<global::System.Decimal> value);
        partial void OnTyLeLYMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TyLeMONO
        {
            get
            {
                return _TyLeMONO;
            }
            set
            {
                OnTyLeMONOChanging(value);
                ReportPropertyChanging("TyLeMONO");
                _TyLeMONO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TyLeMONO");
                OnTyLeMONOChanged();
            }
        }
        private Nullable<global::System.Decimal> _TyLeMONO;
        partial void OnTyLeMONOChanging(Nullable<global::System.Decimal> value);
        partial void OnTyLeMONOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> TyLeGRAN
        {
            get
            {
                return _TyLeGRAN;
            }
            set
            {
                OnTyLeGRANChanging(value);
                ReportPropertyChanging("TyLeGRAN");
                _TyLeGRAN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TyLeGRAN");
                OnTyLeGRANChanged();
            }
        }
        private Nullable<global::System.Decimal> _TyLeGRAN;
        partial void OnTyLeGRANChanging(Nullable<global::System.Decimal> value);
        partial void OnTyLeGRANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HGB
        {
            get
            {
                return _HGB;
            }
            set
            {
                OnHGBChanging(value);
                ReportPropertyChanging("HGB");
                _HGB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HGB");
                OnHGBChanged();
            }
        }
        private Nullable<global::System.Decimal> _HGB;
        partial void OnHGBChanging(Nullable<global::System.Decimal> value);
        partial void OnHGBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RBC
        {
            get
            {
                return _RBC;
            }
            set
            {
                OnRBCChanging(value);
                ReportPropertyChanging("RBC");
                _RBC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RBC");
                OnRBCChanged();
            }
        }
        private Nullable<global::System.Decimal> _RBC;
        partial void OnRBCChanging(Nullable<global::System.Decimal> value);
        partial void OnRBCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MCV
        {
            get
            {
                return _MCV;
            }
            set
            {
                OnMCVChanging(value);
                ReportPropertyChanging("MCV");
                _MCV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MCV");
                OnMCVChanged();
            }
        }
        private Nullable<global::System.Decimal> _MCV;
        partial void OnMCVChanging(Nullable<global::System.Decimal> value);
        partial void OnMCVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MCH
        {
            get
            {
                return _MCH;
            }
            set
            {
                OnMCHChanging(value);
                ReportPropertyChanging("MCH");
                _MCH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MCH");
                OnMCHChanged();
            }
        }
        private Nullable<global::System.Decimal> _MCH;
        partial void OnMCHChanging(Nullable<global::System.Decimal> value);
        partial void OnMCHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MCHC
        {
            get
            {
                return _MCHC;
            }
            set
            {
                OnMCHCChanging(value);
                ReportPropertyChanging("MCHC");
                _MCHC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MCHC");
                OnMCHCChanged();
            }
        }
        private Nullable<global::System.Decimal> _MCHC;
        partial void OnMCHCChanging(Nullable<global::System.Decimal> value);
        partial void OnMCHCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> RDW_CV
        {
            get
            {
                return _RDW_CV;
            }
            set
            {
                OnRDW_CVChanging(value);
                ReportPropertyChanging("RDW_CV");
                _RDW_CV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RDW_CV");
                OnRDW_CVChanged();
            }
        }
        private Nullable<global::System.Decimal> _RDW_CV;
        partial void OnRDW_CVChanging(Nullable<global::System.Decimal> value);
        partial void OnRDW_CVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PLT
        {
            get
            {
                return _PLT;
            }
            set
            {
                OnPLTChanging(value);
                ReportPropertyChanging("PLT");
                _PLT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PLT");
                OnPLTChanged();
            }
        }
        private Nullable<global::System.Decimal> _PLT;
        partial void OnPLTChanging(Nullable<global::System.Decimal> value);
        partial void OnPLTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> MPV
        {
            get
            {
                return _MPV;
            }
            set
            {
                OnMPVChanging(value);
                ReportPropertyChanging("MPV");
                _MPV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MPV");
                OnMPVChanged();
            }
        }
        private Nullable<global::System.Decimal> _MPV;
        partial void OnMPVChanging(Nullable<global::System.Decimal> value);
        partial void OnMPVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PDW
        {
            get
            {
                return _PDW;
            }
            set
            {
                OnPDWChanging(value);
                ReportPropertyChanging("PDW");
                _PDW = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PDW");
                OnPDWChanged();
            }
        }
        private Nullable<global::System.Decimal> _PDW;
        partial void OnPDWChanging(Nullable<global::System.Decimal> value);
        partial void OnPDWChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> PCT
        {
            get
            {
                return _PCT;
            }
            set
            {
                OnPCTChanging(value);
                ReportPropertyChanging("PCT");
                _PCT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PCT");
                OnPCTChanged();
            }
        }
        private Nullable<global::System.Decimal> _PCT;
        partial void OnPCTChanging(Nullable<global::System.Decimal> value);
        partial void OnPCTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Na
        {
            get
            {
                return _Na;
            }
            set
            {
                OnNaChanging(value);
                ReportPropertyChanging("Na");
                _Na = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Na");
                OnNaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Na;
        partial void OnNaChanging(Nullable<global::System.Decimal> value);
        partial void OnNaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> K
        {
            get
            {
                return _K;
            }
            set
            {
                OnKChanging(value);
                ReportPropertyChanging("K");
                _K = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("K");
                OnKChanged();
            }
        }
        private Nullable<global::System.Decimal> _K;
        partial void OnKChanging(Nullable<global::System.Decimal> value);
        partial void OnKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Cl
        {
            get
            {
                return _Cl;
            }
            set
            {
                OnClChanging(value);
                ReportPropertyChanging("Cl");
                _Cl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Cl");
                OnClChanged();
            }
        }
        private Nullable<global::System.Decimal> _Cl;
        partial void OnClChanging(Nullable<global::System.Decimal> value);
        partial void OnClChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Ca
        {
            get
            {
                return _Ca;
            }
            set
            {
                OnCaChanging(value);
                ReportPropertyChanging("Ca");
                _Ca = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ca");
                OnCaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Ca;
        partial void OnCaChanging(Nullable<global::System.Decimal> value);
        partial void OnCaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> HCT
        {
            get
            {
                return _HCT;
            }
            set
            {
                OnHCTChanging(value);
                ReportPropertyChanging("HCT");
                _HCT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HCT");
                OnHCTChanged();
            }
        }
        private Nullable<global::System.Decimal> _HCT;
        partial void OnHCTChanging(Nullable<global::System.Decimal> value);
        partial void OnHCTChanged();

        #endregion
    
    }

    #endregion
    
}
